name: Move Merged PR to Review

on:
  pull_request:
    types: [closed]

jobs:
  move-to-review:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Move Merged PR to Review Column
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: 'Kanban-metrics-h24-grp2-eq3'
          column: 'Revue'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
