name: Opened Issues are in Backlog

on:
  issues:
    types: [unassigned, opened, reopened]

jobs:
  move-to-backlog:
    runs-on: ubuntu-latest
    name: Move to Backlog column
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Common Actions
          column: Backlog
          repo-token: ${{ secrets.github_token }}
